# Testing for measurement invariance with lavaan in R {#lavaan}

## How to Run a MGCFA in R 

Why R? Because it is free.

Alternatives:
  
  * [Mplus](https://www.statmodel.com/)
  
  * [Lisrel](https://ssicentral.com/index.php/products/lisrel/)

## Download R and RStudio

- [RStudio](https://www.rstudio.com/products/rstudio/download/)
- [R](https://cran.r-project.org)

## Install Lavaan and SemTools

- [Lavaan](https://cran.r-project.org/web/packages/lavaan/index.html)
- [semTools](https://cran.r-project.org/web/packages/semTools/index.html)


## Data cleaning

- Do whatever data wrangling necessary (missing values, etc)

- Remember that you need a variable that identifies the group

## Use lavaan language to formalize the model

The [lavaan tutorial](https://lavaan.ugent.be/tutorial/) explains well how to formalize a theoretical model. It even includes a [measurement invariance testing example](https://lavaan.ugent.be/tutorial/groups.html).

In a nutshell:

Factor loadings in R are indicated by =∼ and covariances (between factors or error terms for items) are indicated by ∼∼. The model is specified similar to writing regression equations.

### Example




## Useful shortcut: measurement invariance omnibus testing

```
measurementInvariance(HS.model, 
                      data = HolzingerSwineford1939, 
                      group = "school")
```


```
Measurement invariance models:

Model 1 : fit.configural
Model 2 : fit.loadings
Model 3 : fit.intercepts
Model 4 : fit.means

Chi Square Difference Test

               Df    AIC    BIC  Chisq Chisq diff Df diff Pr(>Chisq)    
fit.configural 48 7484.4 7706.8 115.85                                  
fit.loadings   54 7480.6 7680.8 124.04      8.192       6     0.2244    
fit.intercepts 60 7508.6 7686.6 164.10     40.059       6  4.435e-07 ***
fit.means      63 7543.1 7710.0 204.61     40.502       3  8.338e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Fit measures:

                 cfi rmsea cfi.delta rmsea.delta
fit.configural 0.923 0.097        NA          NA
fit.loadings   0.921 0.093     0.002       0.004
fit.intercepts 0.882 0.107     0.038       0.015
fit.means      0.840 0.122     0.042       0.015

```

Terry Jorgensen [measurementInvariance function](https://www.rdocumentation.org/packages/semTools/versions/0.4-14/topics/measurementInvariance), within the semTools package is very handy



## Advanced Tutorial: Partial Invariance (individually constraining parameters)
